### ISSUE TITLE
Swap without animation?

### ISSUE THREAD

**Issue by hukjordanjanaq** [levibostian/Swapper-Android#8]
The first time, there is no animation. But Is there a way to swap without animation after that?

**Comment by levibostian** [comment]
Great question, @jordanjanaq. Let me see if I can help. 

For all of my apps that I use Swapper, I have always used an animation so I have never encountered this use case before. 

I have a couple of ideas for you to try:
1. Set the animation duration to 0 for the swapper view `swapper_view_instance.animationDuration = 0` (see the readme for documentation on customizing the swapper view instance. 
2. You can customize the source code of this project to meet your needs a little easier. Off the top of my head, you could.....

edit [the function parameters](https://github.com/levibostian/Swapper-Android/blob/f18ab58b98468898fec68cb63f8f4419ac143fc9/swapper/src/main/java/com/levibostian/swapper/SwapperView.kt#L81) to accept an argument:
```kt
@Synchronized fun swapTo(viewToSwapTo: View, onComplete: (() -> Unit)? = null, animate: Bool = true) {
```

then, disable animation [in the function body](https://github.com/levibostian/Swapper-Android/blob/f18ab58b98468898fec68cb63f8f4419ac143fc9/swapper/src/main/java/com/levibostian/swapper/SwapperView.kt#L88)

```kt
if (oldView == null || !animate)
```

---

If you go with option number 2 above and make a pull request into this project I'll accept and merge it 😄

**Comment by hukjordanjanaq** [comment]
Thanks!
